<a href="https://colab.research.google.com/github/StephJones87/Udemy_Biostatistics_Fundamentals/blob/master/Collections.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [2]:
type([1, 2, 3, 4, 5])

list

In [3]:
["Group A", "Group B", "Group C"]

['Group A', 'Group B', 'Group C']

In [0]:
list_1 = [1, 2, 3, 4, 5]

In [5]:
list_1

[1, 2, 3, 4, 5]

In [6]:
len(list_1)

5

In [0]:
import numpy as np

In [8]:
np.sum(list_1) / len(list_1)

3.0

In [9]:
list_1[0]

1

In [10]:
list_1[2]

3

In [11]:
list_1[1:3]

[2, 3]

In [0]:
list_1.append(6)

In [13]:
list_1

[1, 2, 3, 4, 5, 6]

In [14]:
list_1 + [7]

[1, 2, 3, 4, 5, 6, 7]

In [15]:
list_1

[1, 2, 3, 4, 5, 6]

In [0]:
list_1.remove(4)

In [17]:
list_1

[1, 2, 3, 5, 6]

In [18]:
range(10)

range(0, 10)

In [19]:
range(0, 21, 2)

range(0, 21, 2)

In [20]:
[i**2 for i in range(5)]

[0, 1, 4, 9, 16]

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.linspace(1, 12, 6)

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [0]:
dict_1 = {"Pneumonia": 10, "Hypertension": 5, "Diabetes": 4}

In [27]:
type(dict_1)

dict

In [28]:
dict_1.items()

dict_items([('Pneumonia', 10), ('Hypertension', 5), ('Diabetes', 4)])

In [29]:
dict_1.keys()

dict_keys(['Pneumonia', 'Hypertension', 'Diabetes'])

In [30]:
dict_1.values()

dict_values([10, 5, 4])

In [31]:
dict_1["Hypertension"]

5

In [0]:
dict_1.update({"Bronchitis":6})

In [33]:
dict_1

{'Bronchitis': 6, 'Diabetes': 4, 'Hypertension': 5, 'Pneumonia': 10}

In [34]:
dict_1.pop("Hypertension")

5

In [35]:
dict_1

{'Bronchitis': 6, 'Diabetes': 4, 'Pneumonia': 10}

In [0]:
dict_2 = {"Diabetes":{"IDDM":10, "NIDDM":12}, "Hypertension":12}

In [37]:
dict_2

{'Diabetes': {'IDDM': 10, 'NIDDM': 12}, 'Hypertension': 12}

In [38]:
dict_2.values()

dict_values([{'IDDM': 10, 'NIDDM': 12}, 12])